### ISSUE TITLE
lzav and silesia

### ISSUE THREAD

**Issue by avaneev** [flanglet/kanzi-cpp#16]
Hi! Could you please elaborate why in your table "Round-trip scores for LZ" LZAV shows 89232384 bytes compressed size? This is either a mistake or due to the way you compress. LZAV 4.5 compresses silesia tar down to 86495039, if compression is done in-memory as a complete block.

**Comment by flanglet** [comment]
Hi,
I compress the file in 4MB blocks to do a fair comparison with other implementations (same thing with kanzi BTW). Now, when I test with 4.5, I get 88221200 for silesia.tar so I assume you have improved the compression ratio since I tested. I will update the README with this new result. I know you have a code excerpt showing how to use the compressor on your github, but a full working example would lower the effort for users and reduce the risk of misuse.

**Comment by avaneev** [comment]
Thanks. I think you should include this details: that you compress the silesia in 4MB chunks and not the whole file at once.

**Comment by avaneev** [comment]
Sorry for bringing your attention back to lzav, but I wonder why the whole file lzav(2) decompresses 2 times slower than chunked lzav(1), per your test table? Does not make much sense.

**Comment by flanglet** [comment]
Hello, it is not surprising that processing the whole file at once is slower due to higher cost of memory allocation and memory access (see kanzi results). I always run my tests several times, so I am pretty sure about my the numbers. However, I see that the decompression time for lazy is exactly the same as for s2, so I wonder if I did not make a copy mistake? Unfortunately, I will not have access to the test machine for a couple of months. In doubt, I propose to remove the line for "lzav full file at once" until I can check. What do you think?

**Comment by avaneev** [comment]
Well, maybe it's better to place `---` instead of the measurement? That way you'll remember to recheck it. I can't say that's overly important to me, but maybe I've overlooked something that needs to be fixed. `lzbench` now features lzav, there are no issues with full file in-memory decompression speed.

**Comment by flanglet** [comment]
Done.
Let me suggest you add a main.c file to lzav repo so that users can test compression and decompression out of the box.

**Comment by avaneev** [comment]
Thanks. I have a simple CLI tool already, I'll think about posting it. But in my opinion available benchmarks should be enough - if one is serious about selecting a compression algorithm for a project, using lzbench is the only viable option.

**Comment by flanglet** [comment]
My rationale for the CLI is not based on benchmark but simple usage. In order to use LZAV today, users have to write some code and I suspect many, either cannot, or do not want to invest any time doing so. Using LZAV should be as simple as "clone, make, run".
